### ISSUE TITLE
検査実施数のデータ更新を自動化する&ファイルの統合

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19-aichi-tools#1]
本体の下記Issueに対応。

https://github.com/code4nagoya/covid19/issues/167

**Comment by imabari** [comment]
日付を記載内容にあわせたdata.json作成しています
時間については調整が必要です。
https://github.com/imabari/aichi/blob/master/main.py

**Comment by hajime-miyauchi** [comment]
@imabari さん、遅れてすみません。素晴らしいです！
時間取って確認したいと思います。

**Comment by amay077** [comment]
完了したと思いますので close します。
