### ISSUE TITLE
実行環境の docker image が欲しい

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19-aichi-tools#12]
https://github.com/code4nagoya/covid19-aichi-tools/blob/master/README.md を Windows 10 上の WSL Ubuntu でトライしてみましたが、

``pip install -r requirements.txt`` で謎のエラーが出て挫折しました。。。

Python の経験に乏しく、できたら実行環境の docker image を用意してもらえたらなあ、と思います。

docker image があったら、 #4 でも利用できると思います（GitHub Actions で docker image を実行する）。

**Comment by ctyo** [comment]
こちらで対応してみました
https://github.com/code4nagoya/covid19-aichi-tools/pull/14

**Comment by ctyo** [comment]
無事gh-action上でdockerのビルドが走ってファイルが作られるようになったみたいです 🎉 
https://github.com/code4nagoya/covid19-aichi-tools/actions/runs/76041840

**Comment by ctyo** [comment]
無事gh-action上でdockerのビルドが走ってファイルが作られるようになったみたいです 🎉
https://github.com/code4nagoya/covid19-aichi-tools/actions/runs/76041840

**Comment by ctyo** [comment]
無事gh-action上でdockerのビルドが走ってdata.jsonなどのファイルが作られるようになったみたいです 🎉
https://github.com/code4nagoya/covid19-aichi-tools/actions/runs/76041840

**Comment by amay077** [comment]
ありがとうございます、 Dockerfile 使ってトライしてみますね。

**Comment by amay077** [comment]
Dockerfile でスクリプトの動作確認行えました。
Windows だったので改行コード（CRLF だと NG）でハマりましたがｍ

[standard_init_linux.go:211: exec user process caused "no such file or directory"の解決方法 - Qiita](https://qiita.com/SSM3G/items/7ce820f6611213f9e1d6)

で解決できました。
（たぶん、すべての関連ファイルを自力で CRLF → LF 変換しても解決出来たと思います）
