### ISSUE TITLE
scrape_patiants.pyをscrape_patients.pyに修正

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19-aichi-tools#17]
typoしているのでファイル名を変更して欲しい
併せてREADME.mdの実行手順も修正して欲しい

**Comment by sungpyocho** [comment]
初めまして、このリポジトリに貢献したいと思っている愛知県民です。
確かに誤字がありますね。これが私が修正し、PRしてみます。
README.mdの実行手順は、どのように修正したいと思っているんでしょうか？

**Comment by ozo360** [comment]
ありがとうございます。
README.mdの実行手順内に「scrape_patiants.py」の表記がありますので
「scrape_patients.py」に置換していただきたいと思います。

**Comment by ozo360** [comment]
ってもうそのように修正しただいてマージ済みでした！
完了しているのでcloseさせていただきます。
ありがとうございます
