### ISSUE TITLE
data.json - patients_summary に集計最終日に 0件 のデータができる場合がある

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19-aichi-tools#19]
### 集計対象の patients CSV
![image](https://user-images.githubusercontent.com/401369/79177124-fdd5b480-7e3c-11ea-9d4c-0b37933d3e84.png)

### 生成された data.json
https://github.com/code4nagoya/covid19/blob/500052ff6799e09f21c6e56e291d85a2cb368965/data/data.json#L4246-L4249

### 集計実行日時
4/14 AM9:00

## 期待する挙動 / Expected Behavior

patients CSV の末端データ日が 4/12 なので、4/13 のデータは生成されないべき。

**Comment by ozo360** [comment]
@amay077 さんの指摘は最優先で解決されるべきなのは同意です。
付け加えて末尾が 4/12だったとしても、
それ以降を0件としてデータ生成しなくてはいけないケースもあります。
ですのでデータの時点情報を自動取得または、手動でどこかに入力しておいて
そこまでのデータを生成するという処理が必要です。

取り急ぎこのissueはissueで解決されることを願いますが、それで終わりにならないよう注意してください。

**Comment by sungpyocho** [comment]
上に私がこのissueを参照したcommitをしたと書いてありますが、issueナンバーを間違えて参照したので、無視してください。すみません。

**Comment by imabari** [comment]
pandasでしたらindexがDatetimeの場合
df.asfreq("D", fill_value=0)
欠損日付を0で補完してくれます
https://note.nkmk.me/python-pandas-time-series-resample-asfreq/

**Comment by amay077** [comment]
@imabari さんありがとうございます。そのオプションは知らなかったです。
現状 CSV 以外の情報が無いと解決できないのは、

> 末尾が 4/12だったとしても、
> それ以降を0件としてデータ生成しなくてはいけないケースもあります。

で、例えば、集計実施日が 4/15、CSVの末尾が 4/12 だが、4/13～4/14 は
「感染者が居なかった」のか「この CSV が 4/12 時点である」のか判別できないことです。

これは、元の「[県内発生事例一覧(4月22日現在) ［Excelファイル／34KB］](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html)」の "4月22日現在" あるいは EXCEL や PDF の右上に示されている「令和2年4月22日現在」の情報を取得して、「データの時点情報」として考慮する必要があります。

時点情報は、CSV だけでは持つことが難しい（影響範囲がおおきい）ため、現状は保留となっています。

**Comment by imabari** [comment]
最終日付とスクレイピングで取得した日付を比較して追加すればできると思いますが
更新日付を〇月〇日時点と記載しておけば日付がなくても0、日付があっても0ならあまり変わらないような気がします
2/14以降2/24と3/2と3/15の3日だけでそれぞれ連続した日にちではないため
次の日になれば補完されるためあまり影響はないのではないでしょうか？

**Comment by ozo360** [comment]
@imabari さん
@amay077 さんの返信をもう一度よく読んでみてください。

また、システムを扱っている方ならご理解いただけると思いますが、
0件なのか未発表（null）なのかは全く意味が異なります。
このサイトではセンシティブなデータを扱っているという自覚をもっており、
誤った情報を流さないよう十分に配慮をしています。

**Comment by imabari** [comment]
サンプルです
更新日付が含まれない場合は0を追加
https://github.com/imabari/covid19-data/blob/master/aichi/aichi_patients_summary.ipynb

確認のため
愛知県内の感染者・遺伝子検査件数
https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html
3．愛知県内の検査件数
の陽性者数とも合わないのですがこの場合はどちらが正になりますか？
他県でも同じ状態になり検査件数に表示されている陽性者数を採用しました。

**Comment by ozo360** [comment]
issueのタイトルにもあるように「集計最終日」の話をしており、
途中の欠落データについては（一時的に不具合が出ましたが）最初から0件として対応できています。
@amay077 さんの返信はそれを優しく伝えようとしてくれていると思うのですが。

**Comment by amay077** [comment]
続きは
https://github.com/code4nagoya/covid19-aichi-tools/issues/43
に譲り、こちらは close します。
