### ISSUE TITLE
GitHub Actionsを使った自動化で、更新日時が日本時間になっていない

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19-aichi-tools#20]
GitHub Actions での data.json の更新日時の時刻が UTC になっている。

例えば、日本時間 2020/04/14 13:05 に実行された Actions の出力結果の更新日時は 2020/04/14 04:05 になっている。

https://github.com/code4nagoya/covid19/pull/240/files#diff-868ae2d65fb52e0bf680b28558a92a88L3

data.json 生成ツールがタイムゾーンを考慮していないと思われる（これまでローカルで実行していたから問題なかった？）。

**Comment by amay077** [comment]
日本時刻でのデータが前提なので、ツールでは単純に +9:00 としても良いと思います。
（ローカルでも実行したい場合は、パラメータ化すると良いと思います）

**Comment by sungpyocho** [comment]
pythonが提供するdateutilのtz（タイムゾーン）を利用し、日本時間に変えました。
多分これで問題ないと思います。
