### ISSUE TITLE
main_summary - 履歴シートの内容を csv と data.json に出力する

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19-aichi-tools#21]
Google スプレッドシート main_summary - 履歴シート の内容を次の通り csv に出力し、その後 data.json に出力する。

### data/main_summary_history.csv

「検査陽性者状況の推移」のグラフに使用するデータです。

出典元: https://www.pref.aichi.jp/site/covid19-aichi/ の検査陽性者の状況を当サイトで蓄積したデータ

* 下記のヘッダ行が必要です。
* ヘッダ行の各カラム名がそのままJSONに出力されます。

| ヘッダ     | データ                          | 例         |
| ---------- | ------------------------- | ---------- |
| 更新日時 | YYYY/MM/dd HH:mm  | 2020/04/12 23:00 |
| 検査実施人数 | 数値                  | 4372  |
| 陽性患者数   |  数値                   |  324  | 
| 入院中          |  数値                   |  185  | 
| 軽症中等症   |  数値                   |  179  | 
| 重症              |  数値                    | 6  | 
| 施設入所       |  数値                   |  18  | 
| 退院               |  数値                  |  95  | 
| 転院               |  数値                  |  2  | 
| 死亡               |  数値                  |  24  | 
| 備考               |  文字列              | 検査実施人数については4月12日現在。 | 

生成する json の例:

``date:`` は生成日時。

```
"main_summary_history": {
    "date": "2020/04/12 20:00",
    "data": [
      {
            "更新日時": "2020/03/16 22:00",
            "検査実施人数": 1297,
            "陽性患者数": 123,
            "入院中": 97,
            "軽症中等症": 90,
            "重症": 7,
            "施設入所": 0,
            "退院": 11,
            "転院": 1,
            "死亡": 14,
            "備考": ""
        },
    ]
```

https://github.com/code4nagoya/covid19/issues/220 が参照するデータになります。

**Comment by sungpyocho** [comment]
やってみました。一応PRしましたので、確認お願いします。
生成されるjsonは以下の通りです。

![image](https://user-images.githubusercontent.com/38252899/79296982-d56eb880-7f17-11ea-8ab0-61b47e5df1ea.png)
