### ISSUE TITLE
data.json - main_summary の出力をやめる

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19-aichi-tools#25]
https://github.com/code4nagoya/covid19/issues/216#issuecomment-613804123 により、「検査陽性者の状況」は ``main_summary_history`` を参照するようになったため、``main_summary`` は未使用となりました。

そのため、以下の出力を廃止します。

- Google Spreadsheet - main_summary の シート1 の読み込み処理
- main_summary.csv への出力
- data.json の ``main_summary`` 項目

Google Spreadsheet - main_summary の シート1 自体も削除したいですが、
同ドキュメントの「履歴」シートの読み込み処理が シートの順番 に依存している場合は問題になるので、そのあたりが分かる／修正できる方はコメントいただけるとありがたいです。

**Comment by sungpyocho** [comment]
ただいまGoogle Spreadsheetにシートを追加・作成しながら実験を行ってみました。

シート１を削除しても全く問題ありません。読み込みのURLは順番に関係ないユニークなIDを持っています。例えば、
```
$ wget "https://docs.google.com/spreadsheets/d/1DdluQBSQSiACG1CaIg4K3K-HVeGGThyecRHSA84lL6I/export?format=csv&gid=1019512361"
```
で`gid=1019512361`が「履歴」シートのユニークなIDです。

main_summaryの修正は、私が担当してもいいでしょうか？

**Comment by amay077** [comment]
ありがとうございます！
是非お願いします。 :pray:
