### ISSUE TITLE
愛知県HPの感染者一覧が PDF → EXCEL になった

### ISSUE THREAD

**Issue by amay077** [code4nagoya/covid19-aichi-tools#27]
愛知県HP の感染者一覧 https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html が、PDF から EXCEL になってるｗｗｗ
これにより PDF のスクレイピングがエラーになって GitHub Actions が正常な出力をしていないようです。
patients は、
Google Spreadsheet から取得
PDF からスクレイピング
の２段階になっていたようだったので、取り急ぎ Google spreadsheet へ EXCEL の内容を転記しました。

理想としては、
愛知県HP の EXCEL から patients.csv へ直接変換することです。

**Comment by ozo360** [comment]
今日明日くらい目途でゆるくやります。
速くできそうな人がいたらぜひお願いします！

**Comment by hajime-miyauchi** [comment]
え！マジですか！ついに！
