### ISSUE TITLE
GitHub Actionsを使った自動化

### ISSUE THREAD

**Issue by hajime-miyauchi** [code4nagoya/covid19-aichi-tools#4]
GitHub Actionsを使って、下記自動化を実現したい。

- データ生成
- (更新があれば)developmentへの反映
- Pull Requestの作成

**Comment by mikkame** [comment]
https://github.com/code4nagoya/covid19-aichi-tools/blob/master/README.md 
ツールがこれ

**Comment by ctyo** [comment]
こちらで対応してみました。
https://github.com/code4nagoya/covid19-aichi-tools/pull/14

残りはdevelopmentへの反映、PR作成だと思いますが、やり方が謎なので一旦引き継ぎたいです

**Comment by ctyo** [comment]
OK.
9時, 13時, 18時に自動で動作結果ファイルをzipで吐き出すようになりました。
 - https://github.com/code4nagoya/covid19-aichi-tools/actions/runs/76296873

artifactのzipをダウンロードした結果です
```
[~/Desktop/upload-data] $ ls
data.json               inspections_summary.csv main_summary.csv        patients.csv            source.csv              source.pdf
```

この後は何をすればよいでしょうか？

**Comment by amay077** [comment]
こちらはひとまず目的を達成できたと思いますので close します。
新たな要望は新規 issue にて。
