### ISSUE TITLE
inspections_summary.csvに抗原検査件数の列を追加する

### ISSUE THREAD

**Issue by ozo360** [code4nagoya/covid19-aichi-tools#53]
## 改善詳細 / Details of Improvement
- 「愛知県内の検査件数」のスクレイピング結果に抗原検査の3列を追加する
- inspections_summary.csvの仕様変更
- scrape_inspections.pyのスクレイピング処理変更

## 期待する見せ方・挙動 / Expected behavior
- inspections_summary.csvの仕様変更は以下の通り
- 既存のカラム名は他プログラムに影響が出るため変更しないこと

### 現在

検査日 | 件数（件） | 陽性者数（人） | 率（％） | 備考 | 合算
-- | -- | -- | -- | -- | --
2020/07/06 | 130 | 1 | 0.8 | 7月6日（月曜日）

### 抗原検査対応

検査日 | 件数（件） | 陽性者数（人） | 率（％） |  抗原検査_件数（件） | 抗原検査_陽性者数（人） | 抗原検査_率（％） | 備考 | 合算
-- | -- | -- | -- | -- | -- | -- | -- | --
2020/07/06 | 130 | 1 | 0.8 | 6 | 1 | 16.7 | 7月6日（月曜日）

## 関連ISSUE
https://github.com/code4nagoya/covid19/issues/713

**Comment by ozo360** [comment]
「愛知県内の検査件数」の様式が変更になりました。
https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html


検査日 | PCR検査件数（件） | 抗原検査件数（件） | 陽性者数（人） | 率（％）
-- | -- | -- | -- | --  
7月19日（日曜日） | 187 | 0 | 19 | 10.2

これに対応してinspections_summary.csvは以下の仕様に変更しようと思います

検査日 | 件数（件） | 抗原検査件数（件） | 陽性者数（人） | 率（％） | 備考 | 合算
-- | -- | -- | -- | -- | -- | --

**Comment by ozo360** [comment]
仕様変更の再変更に合わせてIssueタイトルを編集しました

**Comment by amay077** [comment]
> 「愛知県内の検査件数」の様式が変更になりました。
> https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html

こちらを対応して、これまで通りのスクレイピングが動作するようになりました。

> これに対応してinspections_summary.csvは以下の仕様に変更しようと思います

こちらの対応は中途半端な状態になっています。

https://github.com/code4nagoya/covid19/blob/2b97230a5932eb247adc17dc868d8ad9d4d1fe77/data/inspections_summary.csv

２列目の列名を「件数（件）」に変える方法が分からなかったので、PDFママの「PCR検査件数（件）」となっています。
正しい列名への変更は別途対応お願いします。

**Comment by ozo360** [comment]
`df.rename(columns = {'PCR検査件数（件）':'件数（件）'}, inplace=True)`
で列名は変更できますけど、
build_json.py側を合わせて変更いただけていますし
この列名の方が適切だと思いますのでこのままにしたいと思います。
ご対応ありがとうございました。

というわけでcloseさせていただきます。

**Comment by ozo360** [comment]
inspections_summary.csvの仕様は以下のようになりました。

| ヘッダ         | データ   | 例                                  |
| -------------- | -------- | ----------------------------------- |
| 検査日           | YYYY/MM/dd | 2020/03/02                          |
| PCR検査件数（件） | 数値     | 639                                 |
| 抗原検査件数（件） | 数値     | 639                                 |
| 陽性者数（人）    | 数値     | 30                                  |
| 率（％）          | 浮動小数点 | 1.98                              |
| 備考             | 文字列   | 1月30日（木曜日）～3月1日（日曜日） |
| 合算             | 文字列   | 〇                                  |
