### ISSUE TITLE
愛知県HPの陽性者一覧PDFが2ファイル化

### ISSUE THREAD

**Issue by takainou** [code4nagoya/covid19-aichi-tools#58]
8/9より[愛知県HP](https://www.pref.aichi.jp/site/covid19-aichi/kansensya-kensa.html)での公開が停止されていた陽性者一覧PDFが、8/13に復活したが、7月までと8月以降の2ファイルとなりました。
新型コロナ県内発生事例一覧表（8月以降） [PDFファイル／375KB]
新型コロナ県内発生事例一覧表（7月まで） [PDFファイル／480KB]

公開停止に伴い、現在は暫定対応として、スプレッドシートに愛知県、名古屋市、豊田市、岡崎市、豊橋市の各所から転記して、取り込んでいます。[#841](https://github.com/code4nagoya/covid19/issues/841)

暫定対応を解除し、愛知県HPの陽性者一覧PDFを取り込むには、2ファイル対応が必要と思われます。

**Comment by amay077** [comment]
現状の仕組みを使っててっとり早く実現するとしたら以下の手順でしょうか。

1. 新型コロナ県内発生事例一覧表（7月まで） の PDF を CSV に変換する → source1.csv とする
2. 新型コロナ県内発生事例一覧表（8月以降） の PDF を CSV に変換する → source2.csv とする
3. シェルスクリプトの cat コマンドで source1.csv と source2.csv を結合する → source.csv とする
4. [これまで通り] source.csv を data.json に変換する
